alias v=`which nvim`
alias k=`which kubectl`
alias kx=`which kubectx`
alias rm="rm -i"
alias p="sudo netstat -ltnp | grep -w "
alias bazel=bazelisk
alias gs="git status"
alias ga="git add ."
alias gpo="git push origin"
alias gc="git commit -m "
